blank_issues_enabled: true
contact_links:
  - name: 💬 Tanya Jawab & Diskusi
    url: https://github.com/wawiwuwawu/amikom-unofficial-app/discussions
    about: Diskusi santai, Q&A, ide fitur, dan koordinasi kontributor.